version: "3.3"

services:
    prevention:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80
        depends_on:
            - db
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: prevention
            DB_USERNAME: root
            DB_PASSWORD: root
    db:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: prevention
            MYSQL_ROOT_PASSWORD: dockerroot
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

volumes:
    db_data:
